# Generated by Django 3.0.4 on 2020-03-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('outid', models.CharField(max_length=200)),
                ('keyapi', models.CharField(max_length=200)),
            ],
        ),
    ]
